### ISSUE TITLE
All tests are failing because wrong jQuery file is referenced

### ISSUE THREAD

**Issue by mide42** [marco-dierenfeldt/MobileTesting#1]
When I clone the repository and open file `index.html` in a browser, then all four tests are failing with the same error message: `ReferenceError: $ is not defined`

The reason for this seems to be that in the header of file `index.html` the library `js/libs/jquery-1.9.1.js` is referenced, but in folder `js\libs` another version of JQuery found, namely `jquery-1.10.2.js`.

Replacing `js/libs/jquery-1.9.1.js` with `js/libs/jquery-1.10.2.js` in file `index.html` fixed the issue for me.

**Comment by marco-dierenfeldt** [comment]
Thank you @mide42 for reporting this issue, I will look into it and fix it.
